import { Layout } from "@/components/Layout";
import { SEOHead } from "@/components/SEOHead";
import { useLanguage } from "@/i18n/LanguageContext";
import type { Language } from "@/i18n/translations";

const sections: Array<{ title: Record<Language, string>; text: Record<Language, string> }> = [
  { title: { es: "Derecho de desistimiento", en: "Right of withdrawal", pl: "Prawo do odstąpienia", de: "Widerrufsrecht", fr: "Droit de rétractation", pt: "Direito de retratação", it: "Diritto di recesso", nl: "Herroepingsrecht" }, text: { es: "Dispones de 14 días naturales desde la recepción del pedido para ejercer tu derecho de desistimiento en productos sin usar, sin abrir y en su embalaje original.", en: "You have 14 calendar days from receipt to exercise your right of withdrawal for unused, unopened products in their original packaging.", pl: "Masz 14 dni kalendarzowych od otrzymania zamówienia na odstąpienie od umowy w przypadku produktów nieużywanych, nieotwieranych i w oryginalnym opakowaniu.", de: "Sie haben 14 Kalendertage ab Erhalt, um Ihr Widerrufsrecht für unbenutzte, ungeöffnete Produkte in Originalverpackung auszuüben.", fr: "Vous disposez de 14 jours calendaires à compter de la réception pour exercer votre droit de rétractation sur des produits non utilisés, non ouverts et dans leur emballage d'origine.", pt: "Tem 14 dias corridos a partir da receção para exercer o seu direito de retratação em produtos não usados, não abertos e na embalagem original.", it: "Hai 14 giorni di calendario dal ricevimento per esercitare il diritto di recesso su prodotti non utilizzati, non aperti e nella confezione originale.", nl: "U heeft 14 kalenderdagen na ontvangst om uw herroepingsrecht uit te oefenen voor ongebruikte, ongeopende producten in de originele verpakking." } },
  { title: { es: "Cambio de fragancia", en: "Fragrance exchange", pl: "Wymiana zapachu", de: "Dufttausch", fr: "Échange de parfum", pt: "Troca de fragrância", it: "Cambio fragranza", nl: "Geurwissel" }, text: { es: "Si la vela llega sin abrir y el aroma no era el esperado, podemos valorar un cambio por otra fragancia. Las velas encendidas, usadas o personalizadas no admiten devolución por preferencia aromática.", en: "If the candle arrives unopened and the scent was not what you expected, we can assess an exchange for another fragrance. Lit, used, or personalized candles are not eligible for return due to scent preference.", pl: "Jeśli świeca dotrze nieotwarta, a zapach nie spełni oczekiwań, możemy rozważyć wymianę na inny aromat. Świece zapalone, używane lub personalizowane nie podlegają zwrotowi z powodu preferencji zapachowej.", de: "Wenn die Kerze ungeöffnet ankommt und der Duft nicht Ihren Erwartungen entspricht, können wir einen Umtausch gegen einen anderen Duft prüfen. Angebrannte, benutzte oder personalisierte Kerzen sind wegen Duftpräferenzen von der Rückgabe ausgeschlossen.", fr: "Si la bougie arrive non ouverte et que le parfum ne correspond pas à vos attentes, nous pouvons étudier un échange contre une autre fragrance. Les bougies allumées, utilisées ou personnalisées ne peuvent pas être retournées pour préférence olfactive.", pt: "Se a vela chegar por abrir e o aroma não corresponder ao esperado, podemos avaliar a troca por outra fragrância. Velas acesas, usadas ou personalizadas não admitem devolução por preferência olfativa.", it: "Se la candela arriva non aperta e la fragranza non è quella attesa, possiamo valutare un cambio con un'altra fragranza. Le candele accese, usate o personalizzate non sono restituibili per preferenza olfattiva.", nl: "Als de kaars ongeopend aankomt en de geur niet was wat u verwachtte, kunnen we een omruiling voor een andere geur beoordelen. Aangestoken, gebruikte of gepersonaliseerde kaarsen komen niet in aanmerking voor retour vanwege geurvoorkeur." } },
  { title: { es: "Productos dañados", en: "Damaged products", pl: "Uszkodzone produkty", de: "Beschädigte Produkte", fr: "Produits endommagés", pt: "Produtos danificados", it: "Prodotti danneggiati", nl: "Beschadigde producten" }, text: { es: "Si tu pedido llega roto o dañado por el transporte, contáctanos en un plazo de 48 horas con fotos del embalaje y del producto. Te ofreceremos reemplazo, cambio o solución equivalente.", en: "If your order arrives broken or damaged in transit, contact us within 48 hours with photos of the packaging and the product. We will offer a replacement, exchange, or equivalent solution.", pl: "Jeśli zamówienie dotrze uszkodzone w transporcie, skontaktuj się z nami w ciągu 48 godzin i prześlij zdjęcia opakowania oraz produktu. Zaproponujemy wymianę lub równoważne rozwiązanie.", de: "Wenn Ihre Bestellung beschädigt ankommt, kontaktieren Sie uns bitte innerhalb von 48 Stunden mit Fotos von Verpackung und Produkt. Wir bieten Ersatz, Umtausch oder eine gleichwertige Lösung an.", fr: "Si votre commande arrive cassée ou endommagée pendant le transport, contactez-nous dans les 48 heures avec des photos de l'emballage et du produit. Nous proposerons un remplacement, un échange ou une solution équivalente.", pt: "Se a sua encomenda chegar partida ou danificada no transporte, contacte-nos no prazo de 48 horas com fotos da embalagem e do produto. Ofereceremos substituição, troca ou solução equivalente.", it: "Se il tuo ordine arriva rotto o danneggiato durante il trasporto, contattaci entro 48 ore con foto dell'imballaggio e del prodotto. Offriremo sostituzione, cambio o soluzione equivalente.", nl: "Als uw bestelling beschadigd aankomt door transport, neem dan binnen 48 uur contact met ons op met foto's van de verpakking en het product. We bieden vervanging, omruiling of een gelijkwaardige oplossing." } },
  { title: { es: "Reembolsos", en: "Refunds", pl: "Zwroty pieniędzy", de: "Rückerstattungen", fr: "Remboursements", pt: "Reembolsos", it: "Rimborsi", nl: "Terugbetalingen" }, text: { es: "Cuando proceda un reembolso, se tramitará por el mismo método de pago en un plazo estimado de 7 a 14 días hábiles desde la validación de la incidencia o recepción del producto devuelto.", en: "When a refund applies, it will be processed through the original payment method within an estimated 7 to 14 business days after the issue is validated or the returned product is received.", pl: "Gdy zwrot środków będzie zasadny, zostanie on zrealizowany tą samą metodą płatności w ciągu około 7-14 dni roboczych od potwierdzenia sprawy lub otrzymania zwróconego produktu.", de: "Soweit eine Rückerstattung erfolgt, wird sie über dieselbe Zahlungsmethode innerhalb von etwa 7 bis 14 Werktagen nach Bestätigung des Vorgangs oder Eingang der Rücksendung bearbeitet.", fr: "Lorsqu'un remboursement est applicable, il sera effectué via le même moyen de paiement dans un délai estimé de 7 à 14 jours ouvrables après validation du dossier ou réception du produit retourné.", pt: "Quando aplicável, o reembolso será processado pelo mesmo método de pagamento no prazo estimado de 7 a 14 dias úteis após a validação da ocorrência ou receção do produto devolvido.", it: "Quando applicabile, il rimborso sarà elaborato con lo stesso metodo di pagamento entro 7-14 giorni lavorativi dalla convalida del problema o dalla ricezione del prodotto restituito.", nl: "Wanneer een terugbetaling van toepassing is, wordt deze via dezelfde betaalmethode verwerkt binnen een geschatte termijn van 7 tot 14 werkdagen nadat het probleem is bevestigd of het geretourneerde product is ontvangen." } },
];

export default function ReturnsPage() {
  const { t, language } = useLanguage();
  return (
    <Layout>
      <SEOHead title={t('returns.title')} description="Política de desistimiento, cambio de fragancia e incidencias de El Aroma de la Vera." canonicalPath="/devoluciones" />
      <section className="gradient-gold section-padding text-center">
        <h1 className="heading-xl mb-4">{t('returns.title')}</h1>
      </section>
      <section className="section-padding">
        <div className="container mx-auto max-w-3xl space-y-8">
          {sections.map((s) => (
            <div key={s.title.en}>
              <h2 className="font-heading text-xl font-semibold mb-3">{s.title[language]}</h2>
              <p className="text-muted-foreground leading-relaxed">{s.text[language]}</p>
            </div>
          ))}
        </div>
      </section>
    </Layout>
  );
}
